/* STAP 1 T/M 3: centrale taalkeuze en subtiele binnenkomst van de secties.
   De HTML bevat Nederlands, zodat de pagina ook zonder JavaScript werkt. */
const translations = {
  nl: {
    navWork: 'Werk',
    navAbout: 'Over mij',
    navContact: 'Contact',
    mainNavigation: 'Hoofdnavigatie',
    heroRole: 'UX/UI Designer & Creative Developer',
    heroLineOne: 'Ik geef ideeën vorm',
    heroLineTwo: 'door te blijven verfijnen',
    introLabel: 'Mijn manier van werken',
    introTitle: 'Een sterk idee ontstaat zelden in één poging.',
    introCopy: 'Ik ontwerp digitale ervaringen en visuele identiteiten door te maken, feedback te zoeken en telkens te verfijnen. Met UX/UI als focus en aandacht voor de details die het verschil maken.',
    selectedWork: 'Geselecteerd werk',
    lumiereTagline: 'Een avond film begint hier.',
    lightLoveTagline: 'Een duidelijkere weg naar hulp en informatie.',
    lightLoveHomePreviewAlt: 'Een scherm uit het vernieuwde websiteprototype voor Licht en Liefde.',
    lumiereAlt: 'Het Lumière-homescherm met filmaanbod, zoekfunctie en navigatie.',
    lumiereDescription: 'Van een film ontdekken tot een avond plannen. Een cinema-app voor tickets, filmaanbod en persoonlijke voorkeuren.',
    schoolProject: 'Schoolopdracht',
    lumiereProcess: 'Onderzoek, user flows, wireframes en een interactief prototype.',
    viewDesign: 'Bekijk het ontwerp',
    burberryJacketAlt: 'Trenchcoat met het ontworpen Burberry-label.',
    burberryKnitAlt: 'Zwarte trui met het Burberry-woordmerk en monogram.',
    personalProject: 'Persoonlijk project',
    burberryProcess: 'Merkonderzoek, identiteit, logo-exploratie en toepassingen.',
    burberryDescription: 'Een rustigere, moderne identiteit die het Britse erfgoed herkenbaar houdt.',
    viewConcept: 'Bekijk het concept',
    viewPreview: 'Bekijk preview',
    workLabel: 'Geselecteerd werk',
    workTitle: 'Werk gevormd door onderzoek, feedback en verfijning.',
    workIntro: 'Onderzoek, ontwerp, testing en uitwerking. Elk project laat zien hoe ik van een vraag naar een verfijnd resultaat werk.',
    contributionLabel: 'Mijn bijdrage',
    lightLoveContribution: 'Een complexe websitestructuur herwerken op basis van onderzoek en zes gebruikerstesten.',
    lightLoveDescription: 'Als teamlead hielp ik de informatiearchitectuur, wireframes en testinzichten samenbrengen in een toegankelijker prototype voor Blindenzorg Licht en Liefde.',
    lightLoveType: 'Schoolproject · echte organisatie · team van 3',
    nextContribution: 'Een warme website voor jongeren testen, verfijnen en samen omzetten in een werkend resultaat.',
    nextDescription: 'Ik hielp met het logo en de gebruikerstesten en bouwde bijna de volledige WonderCMS-website samen met een teamlid.',
    nextType: 'Schoolproject · echte klant · team van 4',
    individualSchoolProject: 'Individuele schoolopdracht',
    lumiereContribution: 'Een complexe filmkeuze terugbrengen tot een heldere, testbare flow.',
    burberryContribution: 'Bekende merkcodes hertekenen tot een rustigere visuele identiteit.',
    openProject: 'Open case study',
    processAria: 'Projectproces',
    researchStep: 'Onderzoek',
    flowsStep: 'Flows',
    prototypeStep: 'Prototype',
    testStep: 'Test',
    sketchStep: 'Schetsen',
    identityStep: 'Identiteit',
    applicationStep: 'Toepassingen',
    cardSortingStep: 'Card sorting',
    informationArchitectureStep: 'Informatiearchitectuur',
    wireframesStep: 'Wireframes',
    moderatedTestingStep: 'Moderated tests',
    usabilityTestingStep: 'Gebruikerstesten',
    brandingStep: 'Branding',
    iterationStep: 'Iteratie',
    developmentStep: 'Development',
    projectsLabel: 'Projecten',
    lightLovePreview: 'Preview van het Licht & Liefde-websiteontwerp',
    nextPreview: 'Preview van het NEXT-websiteontwerp',
    openLightLove: 'Bekijk de Licht & Liefde-case study',
    openLumiere: 'Bekijk de Lumière-case study',
    viewCaseStudy: 'Bekijk de case study',
    openBurberry: 'Bekijk de Burberry-case study',
    aboutLabel: 'Over mij',
    aboutTitle: 'Ik maak ideeën tastbaar.',
    aboutIntro: 'Ik ben Samuel, laatstejaarsstudent Digital Experience Design. Ik gebruik design om mijn creativiteit om te zetten in ervaringen die helder, bruikbaar en visueel sterk zijn.',
    portraitAlt: 'Portret van Samuel Marquez Castro.',
    directionLabel: 'Waarom design',
    directionTitle: 'Ik wilde altijd al dingen maken en ontwerpen om mijn creativiteit te gebruiken.',
    directionCopy: 'Wat mij het meeste energie geeft, is een idee effectief maken en het daarna blijven verbeteren. Door te itereren ontdek ik wat sterker, duidelijker en gebruiksvriendelijker kan.',
    processLabel: 'Hoe ik werk',
    processUnderstandTitle: 'Begrijpen',
    processUnderstandCopy: 'De context, gebruiker en belangrijkste vraag scherp krijgen.',
    processMakeTitle: 'Maken',
    processMakeCopy: 'Ideeën zichtbaar en testbaar maken in flows, wireframes en prototypes.',
    processIterateTitle: 'Itereren',
    processIterateCopy: 'Feedback gebruiken om keuzes te verfijnen en het resultaat sterker te maken.',
    servicesLabel: 'Wat ik doe',
    serviceProduct: 'Onderzoek, user flows, wireframes, prototypes en gebruikerstesten.',
    serviceVisual: 'Visuele identiteit, typografie, compositie en motion.',
    serviceFrontend: 'Responsive interfaces bouwen met HTML, CSS en JavaScript.',
    toolsLabel: 'Tools',
    contactLabel: 'Contact',
    contactTitle: 'Heb je iets in gedachten?',
    contactIntro: 'Ik sta open voor een stage, junior rol, creatieve samenwerking of een goed gesprek over design.',
    contactKicker: 'Stuur me een e-mail',
    availabilityLabel: 'Beschikbaar voor',
    availabilityCopy: 'Stages, junior mogelijkheden en creatieve projecten.',
    focusLabel: 'Focus',
    focusCopy: 'UX/UI, visueel ontwerp en digitale ervaringen.',
    backToWork: 'Terug naar werk',
    caseDeck: 'Een eenvoudiger pad van film ontdekken naar een avond plannen.',
    caseIntro: 'Een individueel appconcept voor Lumière, ontworpen om films, tickets en persoonlijke voorkeuren op een heldere manier samen te brengen.',
    openPrototype: 'Open het Figma-prototype',
    caseOverviewLabel: 'Het project',
    caseOverviewTitle: 'Een eigen appconcept voor Lumière.',
    caseOverviewCopy: 'Voor het vak Lab kreeg ik de opdracht om individueel een app voor Lumière te ontwerpen. Omdat Lumière geen eigen app heeft, werkte ik een zelfstandig concept uit. Bezoekers zouden daarin films kunnen ontdekken, tickets kiezen en via een account voorkeuren zoals hun locatie bewaren.',
    caseContextLabel: 'Context',
    caseContextValue: 'Individuele schoolopdracht · Lab',
    caseRoleLabel: 'Rol',
    caseScopeLabel: 'Aanpak',
    caseScopeValue: 'Onderzoek, flows, wireframes, prototype en gebruikerstest',
    llChapter3: "03 / Nieuwe structuur",
    llTitle3: "Navigatie vanuit bezoekdoelen.",
    llCopy3: "We groepeerden verwante inhoud en gaven belangrijke acties een eigen route. Zo hoefden bezoekers minder te zoeken tussen overlappende categorieën.",
    llChapter4: "04 / Ontwerp",
    llTitle4: "Van structuur naar schermen.",
    llCopy4: "We werkten de navigatie uit in een klikbaar desktopprototype. De homepage biedt duidelijke ingangen; hulp en contact krijgen een vaste, herkenbare plek. Open een scherm om het volledige ontwerp te bekijken.",
    llScreenhome: "Home: overzicht en directe ingangen.",
    llScreenhelp: "Hulp & info: ondersteuning op één plek.",
    llScreencontact: "Contact: formulier en locatie samen.",
    llChapter5: "05 / Gebruikerstest",
    llTitle5: "Zes deelnemers. Concrete verbeterpunten.",
    llCopy5: "We testten het prototype met zes deelnemers: drie sessies werden door de volledige groep gemodereerd, drie tests werden apart uitgevoerd. We observeerden waar mensen twijfelden bij dezelfde zes kerntaken.",
    llTaskSummary: "Bekijk de zes testtaken",
    llFinding0: "Workshops onder activiteiten",
    llEvidence0: "Deelnemers twijfelden tussen Activiteiten en Nieuws & events.",
    llResponse0: "Workshops kregen een plek onder Activiteiten, met een scherper onderscheid tussen activiteiten en nieuws.",
    llFinding1: "Het organisatieverhaal dichterbij",
    llEvidence1: "De historiek werd onder Wie zijn wij verwacht, maar zat te diep.",
    llResponse1: "We verkortten de route en maakten het organisatieverhaal zichtbaarder.",
    llFinding2: "Duidelijkere acties en tekst",
    llEvidence2: "Actieknoppen verschilden in zichtbaarheid. Een deelnemer benoemde kleine tekst en te veel keuzes.",
    llResponse2: "We vereenvoudigden teksten en stemden titels en actieknoppen beter op elkaar af.",
    llFinding3: "Een vertrouwde plek behouden",
    llEvidence3: "Contactgegevens en het adres werden snel in de footer gevonden.",
    llResponse3: "We behielden die voorspelbare plek. Niet elk onderdeel vroeg om een nieuwe oplossing.",
    llChapter6: "06 / Resultaat & reflectie",
    llTitle6: "Een onderbouwd prototype. Een andere blik op structuur.",
    llCopy6: "Het resultaat is een interactief desktopprototype met een nieuwe informatiearchitectuur en verfijningen op basis van gebruikerstesten. Het werd niet als officiële website gelanceerd; we hebben dus geen meetbare impact op echte bezoekers vastgesteld.",
    llLearningTitle: "Wat ik meeneem",
    llLearning: "Als teamlead leerde ik onderzoek, feedback en ontwerpbeslissingen samenbrengen. Vooral het testen bleef hangen: een label kan voor ons logisch klinken, terwijl een bezoeker er iets anders verwacht. Ik wil die aannames eerder toetsen en mijn keuzes blijven onderbouwen met wat mensen daadwerkelijk doen.",
    llDeck: "Een duidelijkere weg naar hulp en informatie.",
    llIntro: "Een schoolproject voor een echte organisatie. Met drie studenten onderzochten we hoe bezoekers hun weg vinden op de website van Blindenzorg Licht en Liefde.",
    llContextLabel: "01 / Context",
    llContextTitle: "Veel informatie. Moeilijk je weg vinden.",
    llContextCopy: "Mensen met een visuele beperking, naasten en vrijwilligers zoeken elk iets anders. Op de bestaande website overlapten categorieën en waren pagina’s moeilijk terug te vinden. Onze opdracht: de inhoud begrijpelijker organiseren en de nieuwe structuur testen.",
    llRoleCopy: "Als teamlead hielp ik het onderzoek organiseren en werkte ik mee aan card sorting, wireframes en gebruikerstesten.",
    llMapSummary: "Bekijk de analyse van de bestaande website",
    llResearchLabel: "02 / Onderzoek",
    llResearchTitle: "Hoe groeperen bezoekers de inhoud?",
    llResearchCopy: "We voerden een open card sort uit met drie deelnemers. Elk teamlid begeleidde één sessie. Deelnemers groepeerden de websiteonderdelen en benoemden hun categorieën zelf.",
    llEvidenceCaption: "Een uitsnede uit de card sorting: gegroepeerde inhoud en labels van een deelnemer. Persoonsgegevens zijn weggelaten.",
    llTakeawayTitle: "De bezoeker denkt vanuit een doel.",
    llTakeawayCopy: "De labels verschilden, maar doelen keerden terug: hulp vinden, deelnemen of de organisatie ondersteunen. Dat werd het vertrekpunt voor de nieuwe navigatie.",
    lightLoveCaseDeck: 'Van complexe informatie naar een duidelijker pad voor hulp, activiteiten en betrokkenheid.',
    lightLoveCaseIntro: 'Voor User Centered Design II onderzochten we met drie studenten hoe de website van Blindenzorg Licht en Liefde duidelijker kon worden. Als teamlead hielp ik onderzoek, structuur, wireframes en gebruikerstesten samenbrengen in een toegankelijker prototype.',
    lightLoveOverviewTitle: 'Een complexe website begint bij de structuur.',
    lightLoveOverviewCopy: 'Blindenzorg Licht en Liefde bedient mensen met een visuele beperking, familieleden, vrijwilligers en professionals. De bestaande website bevatte veel waardevolle informatie, maar onderdelen waren moeilijk terug te vinden en categorieën overlapten. Daarom onderzochten we eerst hoe gebruikers de inhoud zelf begrijpen en groeperen.',
    lightLoveContextValue: 'Groepsproject · UCD II · echte organisatie',
    lightLoveRoleValue: 'Team lead & UX/UI Designer',
    lightLoveTeamLabel: 'Team',
    lightLoveTeamValue: '3 studenten',
    lightLoveScopeValue: 'Analyse, card sorting, informatiearchitectuur en 6 gebruikerstesten',
    lightLoveResultLabel: 'Resultaat',
    lightLoveResultValue: 'Interactief desktopprototype',
    lightLoveChallengeLabel: 'De uitdaging',
    lightLoveChallengeTitle: 'Veel informatie, maar geen vanzelfsprekende route.',
    lightLoveChallengeCopy: "De website richt zich tot mensen met een visuele beperking, familieleden, vrijwilligers, professionals en bezoekers die ondersteuning zoeken. In de bestaande structuur waren pagina's moeilijk terug te vinden, overlapten categorieën en stond veel informatie tegelijk in beeld. We brachten daarom eerst de volledige website in kaart.",
    lightLoveMindmapAria: 'Horizontaal scrollbare mindmap van de bestaande website',
    lightLoveMindmapAlt: 'Mindmap van de bestaande websitestructuur van Blindenzorg Licht en Liefde.',
    lightLoveMindmapCaption: "De AS-IS-mindmap maakte zichtbaar hoeveel bestemmingen, subpagina's en doelgroepen de navigatie tegelijk moest ondersteunen. Scroll horizontaal om het schema te verkennen.",
    lightLoveCardLabel: 'Card sorting',
    lightLoveCardTitle: 'Eerst begrijpen hoe gebruikers informatie groeperen.',
    lightLoveCardCopy: 'We kozen voor een kwalitatieve open card sort. Elk teamlid begeleidde één sessie: drie deelnemers groepeerden onderdelen van de bestaande website en gaven hun categorieën zelf een naam. Zo konden we vergelijken welke verbanden natuurlijk aanvoelden.',
    lightLoveCardAlt: 'Geanonimiseerde card-sortresultaten met gegroepeerde websiteonderdelen.',
    lightLoveCardAria: 'Horizontaal scrollbare uitsnede van de card-sortresultaten',
    lightLoveCardCaption: "Geanonimiseerde uitsnede uit een echte testsessie. Namen, foto's en profielgegevens zijn bewust weggelaten.",
    lightLoveParticipants: 'deelnemers',
    lightLoveMethodCopy: 'Dezelfde content leverde verschillende labels op, maar de onderliggende bezoekdoelen kwamen terug: informatie vinden, deelnemen, helpen, de organisatie leren kennen of contact opnemen.',
    lightLoveClustersAria: 'Terugkerende groepen',
    lightLoveClusterKnowledge: 'Hulp & kennis',
    lightLoveClusterActivities: 'Activiteiten & nieuws',
    lightLoveClusterOrganisation: 'De organisatie',
    lightLoveClusterSupport: 'Helpen & deelnemen',
    lightLoveClusterContact: 'Contact',
    lightLoveClusterAccount: 'Account',
    lightLoveInsightLabel: 'Belangrijk inzicht',
    lightLoveInsightTitle: 'De structuur moet vertrekken vanuit wat iemand wil doen.',
    lightLoveInsightCopy: 'Iemand die informatie over een visuele beperking zoekt, denkt anders dan iemand die vrijwilliger wil worden. Dat verschil gaf ons een duidelijke basis voor de nieuwe informatiearchitectuur.',
    lightLoveArchitectureLabel: 'Nieuwe structuur',
    lightLoveArchitectureTitle: "Van losse pagina's naar duidelijke bestemmingen.",
    lightLoveArchitectureCopy: 'De card sorting bevestigde dat bezoekers vooral denken vanuit hun doel. Daarom vereenvoudigden we de navigatie, groepeerden we gerelateerde inhoud opnieuw en gaven we belangrijke acties een eigen, herkenbare route.',
    lightLoveArchitecturePathAria: 'Van analyse naar nieuwe navigatie',
    lightLoveArchitectureStepOne: 'Bestaande structuur',
    lightLoveArchitectureStepOneCopy: "Alle pagina's en afhankelijkheden zichtbaar maken.",
    lightLoveArchitectureStepTwo: 'Gebruikerslogica',
    lightLoveArchitectureStepTwoCopy: 'Terugkerende groepen en benamingen vergelijken.',
    lightLoveArchitectureStepThree: 'Nieuwe navigatie',
    lightLoveArchitectureStepThreeCopy: 'Inhoud ordenen rond informatie, deelname en actie.',
    lightLoveToBeLabel: 'TO-BE navigatie',
    lightLoveHomeNode: 'Home als helder vertrekpunt',
    lightLoveInformationGroup: 'Informatie vinden',
    lightLoveActionGroup: 'Iets doen',
    lightLoveSupportGroup: 'Ondersteunende routes',
    lightLoveNavHelp: 'Hulp & info',
    lightLoveNavActivities: 'Activiteiten',
    lightLoveNavAbout: 'Wie zijn wij',
    lightLoveNavNews: 'Nieuws & events',
    lightLoveNavVolunteer: 'Vrijwilliger worden',
    lightLoveNavDonate: 'Doneren',
    lightLoveNavContact: 'Contact opnemen',
    lightLoveSupportRoutes: 'FAQ · Historiek · Detail nieuws · Registreren · Loginroutes',
    lightLoveArchitectureDecisionLabel: 'Ontwerpbeslissing',
    lightLoveArchitectureDecisionCopy: "Doneren, vrijwilliger worden en contact opnemen werden geen verborgen eindpunten. Ze kregen een duidelijke eigen route, terwijl inhoudelijke pagina's onder herkenbare bestemmingen werden gegroepeerd.",
    lightLovePrototypeLabel: 'Uitwerking',
    lightLovePrototypeTitle: 'Een structuur wordt pas bruikbaar in echte schermen.',
    lightLovePrototypeCopy: 'We vertaalden de nieuwe navigatie naar een uitgebreid desktopprototype. Duidelijke paginatitels, herkenbare routes en vaste plekken voor navigatie en contact moesten bezoekers sneller oriënteren.',
    lightLoveHomeScreenAria: 'Horizontaal verkenbaar ontwerp van de homepage',
    lightLoveHomeScreenAlt: 'Ontworpen homepage voor Blindenzorg Licht en Liefde.',
    lightLoveHomeScreenCaption: 'Home — overzicht, herkenbare ingangen en zichtbare primaire acties.',
    lightLoveHelpScreenAria: 'Horizontaal verkenbaar ontwerp van de pagina Hulp en info',
    lightLoveHelpScreenAlt: 'Ontworpen pagina Hulp en info voor Blindenzorg Licht en Liefde.',
    lightLoveHelpScreenCaption: 'Hulp & info — inhoudelijke ondersteuning gegroepeerd onder één duidelijke bestemming.',
    lightLoveContactScreenAria: 'Horizontaal verkenbaar ontwerp van de contactpagina',
    lightLoveContactScreenAlt: 'Ontworpen contactpagina voor Blindenzorg Licht en Liefde.',
    lightLoveContactScreenCaption: 'Contact — formulier en locatie-informatie samen op een voorspelbare plek.',
    lightLovePrototypeNote: 'Het prototype focust op desktop. Die keuze gaf ons ruimte om de complexe inhoud en navigatiestructuur eerst volledig uit te werken en daarna gericht te testen.',
    lightLoveTestingLabel: 'Gebruikstest',
    lightLoveTestingTitle: 'Niet vragen of het duidelijk is. Kijken waar iemand vastloopt.',
    lightLoveTestingCopy: 'We testten het klikbare prototype met zes deelnemers. Drie sessies werden door de volledige projectgroep gemodereerd; drie aanvullende tests werden apart uitgevoerd. Met dezelfde kerntaken konden we terugkerende patronen vergelijken zonder losse meningen als bewijs te behandelen.',
    lightLoveTestParticipants: 'deelnemers',
    lightLoveTestFactOne: 'Klikbaar desktopprototype in Figma',
    lightLoveTestFactTwo: 'Think-aloud en taakgerichte observatie',
    lightLoveTestFactThree: '3 groepsgemodereerde en 3 aanvullende tests',
    lightLoveTasksLabel: '6 kerntaken',
    lightLoveTaskOne: 'Informatie over een visuele beperking vinden',
    lightLoveTaskTwo: 'Vrijwilliger worden',
    lightLoveTaskThree: 'Een workshop of activiteit zoeken',
    lightLoveTaskFour: 'Contact opnemen',
    lightLoveTaskFive: 'Een donatie starten',
    lightLoveTaskSix: 'De historiek terugvinden',
    lightLoveFindingsLabel: 'Wat we leerden',
    lightLoveFindingsTitle: 'Vier patronen bepaalden wat er nog moest veranderen.',
    lightLoveFindingsCopy: 'Niet elke deelnemer volgde exact dezelfde route. Dezelfde momenten van twijfel kwamen wel meerdere keren terug. Die patronen gaven ons concrete prioriteiten voor de volgende iteratie.',
    lightLoveFindingOneTitle: 'Workshops voelden als activiteiten.',
    lightLoveFindingOneEvidence: 'Deelnemers zochten workshops eerst onder Activiteiten en twijfelden daarna tussen Activiteiten en Nieuws & events.',
    lightLoveFindingOneResponse: 'Daarom brachten we workshops rechtstreeks onder Activiteiten en maakten we het onderscheid met nieuws scherper.',
    lightLoveFindingTwoTitle: 'De historiek zat te diep verborgen.',
    lightLoveFindingTwoEvidence: 'Gebruikers verwachtten het verhaal van de organisatie onder Wie zijn wij, maar vonden de historiek pas na meerdere stappen.',
    lightLoveFindingTwoResponse: 'We maakten de route naar het organisatieverhaal zichtbaarder en verkortten de weg ernaartoe.',
    lightLoveFindingThreeTitle: 'Belangrijke acties moesten consistenter.',
    lightLoveFindingThreeEvidence: "Vrijwilligen en doneren werden meestal gevonden, maar CTA's verschilden in zichtbaarheid. Een oudere deelnemer benoemde ook kleine tekst en te veel keuzes.",
    lightLoveFindingThreeResponse: 'We vereenvoudigden teksten, verduidelijkten titels en stemden de grootte en nadruk van actieknoppen beter op elkaar af.',
    lightLoveFindingFourTitle: 'De footer werkte als betrouwbaar ankerpunt.',
    lightLoveFindingFourEvidence: 'Contactgegevens en het adres werden snel en zonder twijfel onderaan de pagina gevonden.',
    lightLoveFindingFourResponse: 'Die voorspelbare plek behielden we bewust in plaats van een werkend patroon opnieuw uit te vinden.',
    lightLoveOutcomeLabel: 'Eindresultaat',
    lightLoveOutcomeTitle: 'Een onderbouwd prototype voor complexe informatie.',
    lightLoveOutcomeCopy: "Het resultaat is een uitgebreid desktopprototype waarin de nieuwe structuur wordt toegepast op de belangrijkste informatie- en actiepagina's. Het werd niet als officiële website gelanceerd; de waarde van het project zit in het volledige traject van analyse tot geteste verfijning.",
    lightLoveOutcomeOne: 'Nieuwe informatiearchitectuur',
    lightLoveOutcomeTwo: 'Klikbaar desktopprototype',
    lightLoveOutcomeThree: 'Testgestuurde verfijning',
    lightLoveReflectionLabel: 'Reflectie',
    lightLoveReflectionTitle: 'Een duidelijke interface begint vóór het eerste scherm.',
    lightLoveReflectionCopy: 'Dit project liet me zien hoe sterk informatiearchitectuur de volledige gebruikservaring beïnvloedt. Als teamlead leerde ik onderzoek, feedback en ontwerpbeslissingen samenbrengen zonder het proces te vertragen. De tests maakten ook duidelijk dat een logisch klinkend label nog niet betekent dat gebruikers weten waar ze moeten zoeken.',
    lightLoveContributionLabel: 'Mijn bijdrage binnen het team',
    lightLoveContributionOne: 'Het proces en de feedbackmomenten mee structureren als teamlead',
    lightLoveContributionTwo: 'Bijdragen aan card sorting, informatiearchitectuur en wireframes',
    lightLoveContributionThree: 'Gebruikertesten begeleiden en bevindingen vertalen naar iteraties',
    lightLoveViewAllWork: 'Bekijk alle projecten',
    caseQuestionLabel: 'De ontwerpvraag',
    caseQuestionTitle: 'Hoe maak je kiezen eenvoudiger zonder de mogelijkheden te verliezen?',
    caseQuestionCopy: 'Een cinema-app moet informatie over films en planning bieden, maar de keuze voor een film mag niet overweldigend worden. Die spanning tussen mogelijkheden en overzicht bepaalde de richting van het ontwerp.',
    caseFlowLabel: 'Structuur',
    caseFlowTitle: 'Eerst de routes, dan de schermen.',
    caseFlowCopy: 'Ik bracht mogelijke stappen en functies in kaart: van een film vinden tot informatie bekijken en tickets kiezen. De flowchart toont hoe breed het concept aanvankelijk was en gaf een basis om de interface te ordenen.',
    caseFlowAria: 'Scrollbare Lumière-flowchart',
    caseFlowAlt: 'Flowchart van het appconcept met routes van de start naar home, filmaanbod, account en tickets.',
    caseFlowCaption: 'De informatiestructuur van het appconcept. Scroll horizontaal om het schema in detail te bekijken.',
    caseEvolutionLabel: 'Uitwerking',
    caseEvolutionTitle: 'Van structuur naar een herkenbare interface.',
    caseEvolutionCopy: 'Het homescherm ontwikkelde zich van een eenvoudige indeling naar een visueel uitgewerkt ontwerp. De drie versies laten zien hoe inhoud, beeld en navigatie hun plaats kregen.',
    caseLowAlt: 'Eerste low-fidelity versie van het Lumière-homescherm.',
    caseLowLabel: 'Eerste indeling',
    caseMidAlt: 'Mid-fidelity versie waarin het beeld en de inhoud worden geplaatst.',
    caseMidLabel: 'Inhoud en hiërarchie',
    caseHighAlt: 'Uitgewerkte high-fidelity versie van het Lumière-homescherm.',
    caseHighLabel: 'Visuele uitwerking',
    caseInsightLabel: 'Gebruikertest',
    caseInsightTitle: 'Een film kiezen moet eenvoudig blijven.',
    caseInsightCopy: 'Uit de gebruikerstest kwam naar voren dat te veel opties of een druk scherm mensen kunnen verwarren wanneer ze een film kiezen. Dat inzicht maakte eenvoud en duidelijke keuzes belangrijk in de beoordeling van het ontwerp.',
    caseOutcomeLabel: 'Het resultaat',
    caseOutcomeTitle: 'Een interactief prototype als resultaat.',
    caseOutcomeCopy: 'Het resultaat is een uitgewerkt homescherm en een interactief Figma-prototype van het bredere appconcept. Het project leerde me om functies steeds af te wegen tegen de eenvoud van de ervaring.',
    caseNextAria: 'Verder navigeren',
    burberryCaseDeck: 'Erfgoed, opnieuw in balans.',
    burberryCaseIntro: 'Een persoonlijke rebrandstudie: hoe kan een herkenbaar luxemerk rustiger en moderner aanvoelen zonder zijn Britse karakter te verliezen?',
    burberryOverviewTitle: 'Geen nieuw merk. Een scherpere selectie.',
    burberryOverviewCopy: "Voor dit persoonlijke PET-project onderzocht ik hoe Burberry's bekende merkcodes met meer terughoudendheid kunnen worden ingezet. De trenchcoat, de check en de historische ruiter vormden het vertrekpunt. Mijn rol was Brand Designer, van onderzoek en logo-exploratie tot de uitwerking op kleding.",
    burberryContextValue: 'Persoonlijk PET-project · conceptuele rebrand',
    burberryScopeValue: 'Merkonderzoek, schetsen, logo en kledingtoepassingen',
    burberryDirectionLabel: 'De richting',
    burberryDirectionTitle: 'Wat blijft herkenbaar als je de ruis wegneemt?',
    burberryDirectionCopy: 'De studie vertrekt vanuit quiet luxury met archieferfgoed. Minder visuele drukte, meer aandacht voor typografie en ruimte, en historische verwijzingen die als detail werken in plaats van als decoratie.',
    burberryExplorationLabel: 'Exploratie',
    burberryExplorationTitle: 'Eerst zoeken op papier.',
    burberryExplorationCopy: 'In de eerste schetsen onderzocht ik varianten op de B, het schild en de historische ruiter. Die verkenning hielp om een compact symbool te kiezen dat op een kledingstuk ook in klein formaat zichtbaar kan blijven.',
    burberrySketchAlt: 'Blad met potloodschetsen van Burberry-monogrammen, schilden en een ruiter.',
    burberrySketchCaption: 'Logo-exploratie: van ruiter en initialen naar een eenvoudiger teken.',
    burberryIdentityLabel: 'Identiteit',
    burberryIdentityTitle: 'Een schild als stille verwijzing.',
    burberryIdentityCopy: 'Het uitgewerkte symbool combineert een B met een schild en een verticale lijn. Zo blijft de verwijzing naar bescherming en vooruitgang aanwezig, zonder de volledige historische illustratie over te nemen. Een serif woordmerk zorgt voor de editorial tegenhanger.',
    burberryMarkAlt: 'Het ontworpen Burberry-logo met schildsymbool en woordmerk.',
    burberryMarkCaption: 'Het volledige logo uit het originele SVG-ontwerpbestand.',
    burberryPaletteAria: 'Kleurpalet van het concept',
    burberryPaletteCopy: 'Ivoor en zwart dragen de identiteit; beige verwijst subtiel naar de trenchcoat.',
    burberryApplicationsLabel: 'Toepassingen',
    burberryApplicationsTitle: 'Het ontwerp op kleding.',
    burberryApplicationsCopy: 'De toepassingen laten twee schaalniveaus zien: een zichtbaar woordmerk met symbool op de zwarte trui en een terughoudender merkteken als detail op de trenchcoat en de donkerblauwe sweater. Het zijn conceptuele mockups, geen geproduceerde kledingstukken.',
    burberryCoatDetailAlt: 'Trenchcoat met Burberry-label en subtiele merkdetails.',
    burberryCoatCaption: '01 / Trenchcoat en label',
    burberryKnitDetailAlt: 'Zwarte trui met groot Burberry-woordmerk en schildsymbool.',
    burberryKnitCaption: '02 / Woordmerk en symbool',
    burberrySweaterAlt: 'Donkerblauwe sweater met klein schildsymbool op de borst.',
    burberrySweaterCaption: '03 / Symbool als detail',
    burberryReflectionLabel: 'Reflectie',
    burberryReflectionTitle: 'De kracht zit in wat je weglaat.',
    burberryReflectionCopy: 'Dit project liet me werken met bestaande merkcodes in plaats van vanaf nul te beginnen. De schetsen, het symbool en de kledingmockups tonen de gekozen richting. Andere dragers zoals verpakking of een website zijn ideeën in de projecttekst, maar maken geen deel uit van deze uitgewerkte selectie.',
    burberryNextProject: 'Bekijk Lumière',
    footerRole: 'Designer & Developer met een focus op UX/UI.',
    skip: 'Naar de inhoud',
    language: 'Taalkeuze',
    description: 'Samuel Marquez Castro. Designer & Developer met een focus op UX/UI en visueel ontwerp.'
  },
  en: {
    navWork: 'Work',
    navAbout: 'About',
    navContact: 'Contact',
    mainNavigation: 'Main navigation',
    heroRole: 'UX/UI Designer & Creative Developer',
    heroLineOne: 'I shape ideas',
    heroLineTwo: 'through iteration',
    introLabel: 'How I work',
    introTitle: 'A strong idea rarely happens in one attempt.',
    introCopy: 'I design digital experiences and visual identities by making, seeking feedback and refining each iteration. Focused on UX/UI, with attention to the details that make a difference.',
    selectedWork: 'Selected work',
    lumiereTagline: 'A night at the movies starts here.',
    lightLoveTagline: 'A clearer path to help and information.',
    lightLoveHomePreviewAlt: 'A screen from the redesigned Licht en Liefde website prototype.',
    lumiereAlt: 'The Lumière home screen with film listings, search and navigation.',
    lumiereDescription: 'From discovering a film to planning a night out. A cinema app for tickets, film listings and personal preferences.',
    schoolProject: 'School project',
    lumiereProcess: 'Research, user flows, wireframes and an interactive prototype.',
    viewDesign: 'View the design',
    burberryJacketAlt: 'Trench coat with the redesigned Burberry label.',
    burberryKnitAlt: 'Black knit with the Burberry wordmark and monogram.',
    personalProject: 'Personal project',
    burberryProcess: 'Brand research, identity, logo exploration and applications.',
    burberryDescription: 'A calmer, modern identity that keeps its British heritage recognisable.',
    viewConcept: 'View the concept',
    viewPreview: 'View preview',
    workLabel: 'Selected work',
    workTitle: 'Work shaped by research, feedback and refinement.',
    workIntro: 'Research, design, testing and delivery. Each project shows how I move from a question to a refined result.',
    contributionLabel: 'My contribution',
    lightLoveContribution: 'Restructuring a complex website through research and six usability tests.',
    lightLoveDescription: 'As team lead, I helped bring information architecture, wireframes and test insights together in a more accessible prototype for Blindenzorg Licht en Liefde.',
    lightLoveType: 'School project · real organisation · team of 3',
    nextContribution: 'Testing and refining a warm website for young people, then helping turn it into a working result.',
    nextDescription: 'I contributed to the logo and usability testing and built almost the entire WonderCMS website together with a teammate.',
    nextType: 'School project · real client · team of 4',
    individualSchoolProject: 'Individual school project',
    lumiereContribution: 'Turning a complex film choice into a clear, testable flow.',
    burberryContribution: 'Redrawing familiar brand codes into a calmer visual identity.',
    openProject: 'Open case study',
    processAria: 'Project process',
    researchStep: 'Research',
    flowsStep: 'Flows',
    prototypeStep: 'Prototype',
    testStep: 'Test',
    sketchStep: 'Sketches',
    identityStep: 'Identity',
    applicationStep: 'Applications',
    cardSortingStep: 'Card sorting',
    informationArchitectureStep: 'Information architecture',
    wireframesStep: 'Wireframes',
    moderatedTestingStep: 'Moderated tests',
    usabilityTestingStep: 'Usability testing',
    brandingStep: 'Branding',
    iterationStep: 'Iteration',
    developmentStep: 'Development',
    projectsLabel: 'Projects',
    lightLovePreview: 'Preview of the Licht & Liefde website design',
    nextPreview: 'Preview of the NEXT website design',
    openLightLove: 'View the Licht & Liefde case study',
    openLumiere: 'View the Lumière case study',
    viewCaseStudy: 'View the case study',
    openBurberry: 'View the Burberry case study',
    aboutLabel: 'About',
    aboutTitle: 'I make ideas tangible.',
    aboutIntro: 'I’m Samuel, a final-year Digital Experience Design student. I use design to turn my creativity into experiences that are clear, useful and visually strong.',
    portraitAlt: 'Portrait of Samuel Marquez Castro.',
    directionLabel: 'Why design',
    directionTitle: 'I have always wanted to make and design things as a way to use my creativity.',
    directionCopy: 'What gives me the most energy is turning an idea into something real and then continuing to improve it. Iteration helps me discover what can be stronger, clearer and easier to use.',
    processLabel: 'How I work',
    processUnderstandTitle: 'Understand',
    processUnderstandCopy: 'Define the context, the user and the question that matters most.',
    processMakeTitle: 'Make',
    processMakeCopy: 'Make ideas visible and testable through flows, wireframes and prototypes.',
    processIterateTitle: 'Iterate',
    processIterateCopy: 'Use feedback to refine decisions and make the result stronger.',
    servicesLabel: 'What I do',
    serviceProduct: 'Research, user flows, wireframes, prototypes and usability testing.',
    serviceVisual: 'Visual identity, typography, composition and motion.',
    serviceFrontend: 'Building responsive interfaces with HTML, CSS and JavaScript.',
    toolsLabel: 'Tools',
    contactLabel: 'Contact',
    contactTitle: 'Have something in mind?',
    contactIntro: 'I’m open to an internship, junior role, creative collaboration or a good conversation about design.',
    contactKicker: 'Send me an email',
    availabilityLabel: 'Available for',
    availabilityCopy: 'Internships, junior opportunities and creative projects.',
    focusLabel: 'Focus',
    focusCopy: 'UX/UI, visual design and digital experiences.',
    backToWork: 'Back to work',
    caseDeck: 'A simpler path from discovering a film to planning a night out.',
    caseIntro: 'An individual app concept for Lumière, designed to bring films, tickets and personal preferences together in a clear experience.',
    openPrototype: 'Open the Figma prototype',
    caseOverviewLabel: 'The project',
    caseOverviewTitle: 'An original app concept for Lumière.',
    caseOverviewCopy: 'For my Lab course, I was asked to design an app for Lumière independently. As Lumière does not have an app, I developed a concept of my own. Visitors could discover films, choose tickets and save preferences such as their location in an account.',
    caseContextLabel: 'Context',
    caseContextValue: 'Individual school project · Lab',
    caseRoleLabel: 'Role',
    caseScopeLabel: 'Approach',
    caseScopeValue: 'Research, flows, wireframes, prototype and usability testing',
    llChapter3: "03 / New structure",
    llTitle3: "Navigation built around visitor goals.",
    llCopy3: "We grouped related content and gave important actions their own routes, reducing the need to search across overlapping categories.",
    llChapter4: "04 / Design",
    llTitle4: "From structure to screens.",
    llCopy4: "We developed the navigation into a clickable desktop prototype. The homepage provides clear entry points, with consistent places for support and contact. Open a screen to see the full design.",
    llScreenhome: "Home: an overview and direct entry points.",
    llScreenhelp: "Support & information: guidance in one place.",
    llScreencontact: "Contact: form and location together.",
    llChapter5: "05 / Usability testing",
    llTitle5: "Six participants. Clear areas to improve.",
    llCopy5: "We tested the prototype with six participants: three sessions were moderated by the full team and three tests were conducted separately. We observed hesitation during the same six core tasks.",
    llTaskSummary: "Explore the six test tasks",
    llFinding0: "Workshops under activities",
    llEvidence0: "Participants hesitated between Activities and News & events.",
    llResponse0: "Workshops were placed under Activities, with a clearer distinction between activities and news.",
    llFinding1: "Bringing the organisation’s story closer",
    llEvidence1: "Participants expected the history under About us, but it was buried too deeply.",
    llResponse1: "We shortened the route and made the organisation’s story more visible.",
    llFinding2: "Clearer actions and copy",
    llEvidence2: "Action buttons varied in visibility. One participant mentioned small text and too many choices.",
    llResponse2: "We simplified copy and made headings and action buttons more consistent.",
    llFinding3: "Keeping a familiar location",
    llEvidence3: "Contact details and the address were quickly found in the footer.",
    llResponse3: "We kept that predictable location. Not every part needed a new solution.",
    llChapter6: "06 / Outcome & reflection",
    llTitle6: "An informed prototype. A new perspective on structure.",
    llCopy6: "The outcome is an interactive desktop prototype with a new information architecture and refinements informed by usability tests. It was not launched as the official website, so we have not measured its impact on real visitors.",
    llLearningTitle: "What I take away",
    llLearning: "As team lead, I learned to connect research, feedback and design decisions. Testing stood out: a label can sound logical to us while a visitor expects something else. I want to test those assumptions earlier and keep grounding decisions in what people actually do.",
    llDeck: "A clearer route to support and information.",
    llIntro: "A school project for a real organisation. Our team of three explored how visitors find their way around the Blindenzorg Licht en Liefde website.",
    llContextLabel: "01 / Context",
    llContextTitle: "Plenty of information. Hard to find your way.",
    llContextCopy: "People with a visual impairment, relatives and volunteers each need different things. On the existing website, categories overlapped and pages were difficult to find. Our task: organise the content more clearly and test the new structure.",
    llRoleCopy: "As team lead, I helped organise the research and contributed to card sorting, wireframes and usability testing.",
    llMapSummary: "Explore our analysis of the existing website",
    llResearchLabel: "02 / Research",
    llResearchTitle: "How do visitors group the content?",
    llResearchCopy: "We ran an open card sort with three participants. Each team member facilitated one session. Participants grouped the website content and named their own categories.",
    llEvidenceCaption: "An excerpt from the card sort: content groups and labels created by a participant. Personal details have been removed.",
    llTakeawayTitle: "Visitors start with a goal.",
    llTakeawayCopy: "The labels differed, but goals kept returning: finding support, participating or helping the organisation. These became the starting point for the new navigation.",
    lightLoveCaseDeck: 'From complex information to a clearer path towards support, activities and participation.',
    lightLoveCaseIntro: 'For User Centered Design II, our team of three explored how the Blindenzorg Licht en Liefde website could become clearer. As team lead, I helped bring research, structure, wireframes and usability testing together in a more accessible prototype.',
    lightLoveOverviewTitle: 'A complex website starts with its structure.',
    lightLoveOverviewCopy: 'Blindenzorg Licht en Liefde serves people with a visual impairment, relatives, volunteers and professionals. The existing website contained valuable information, but sections were difficult to find and categories overlapped. We therefore started by researching how users understand and group the content themselves.',
    lightLoveContextValue: 'Group project · UCD II · real organisation',
    lightLoveRoleValue: 'Team lead & UX/UI Designer',
    lightLoveTeamLabel: 'Team',
    lightLoveTeamValue: '3 students',
    lightLoveScopeValue: 'Analysis, card sorting, information architecture and 6 usability tests',
    lightLoveResultLabel: 'Outcome',
    lightLoveResultValue: 'Interactive desktop prototype',
    lightLoveChallengeLabel: 'The challenge',
    lightLoveChallengeTitle: 'A lot of information, without an obvious route.',
    lightLoveChallengeCopy: 'The website serves people with a visual impairment, relatives, volunteers, professionals and visitors looking for support. In the existing structure, pages were difficult to find, categories overlapped and too much information competed for attention. We therefore started by mapping the complete website.',
    lightLoveMindmapAria: 'Horizontally scrollable mind map of the existing website',
    lightLoveMindmapAlt: 'Mind map of the existing Blindenzorg Licht en Liefde website structure.',
    lightLoveMindmapCaption: 'The AS-IS mind map revealed how many destinations, subpages and audiences the navigation had to support at once. Scroll horizontally to explore the structure.',
    lightLoveCardLabel: 'Card sorting',
    lightLoveCardTitle: 'First understand how users group information.',
    lightLoveCardCopy: 'We chose a qualitative open card sort. Each team member facilitated one session: three participants grouped parts of the existing website and named their own categories. This allowed us to compare which relationships felt natural.',
    lightLoveCardAlt: 'Anonymised card-sorting results with grouped website content.',
    lightLoveCardAria: 'Horizontally scrollable excerpt of the card-sorting results',
    lightLoveCardCaption: 'An anonymised excerpt from a real test session. Names, photographs and profile details have deliberately been removed.',
    lightLoveParticipants: 'participants',
    lightLoveMethodCopy: 'The same content produced different labels, but the underlying visitor goals kept returning: finding information, participating, helping, learning about the organisation or getting in touch.',
    lightLoveClustersAria: 'Recurring groups',
    lightLoveClusterKnowledge: 'Support & knowledge',
    lightLoveClusterActivities: 'Activities & news',
    lightLoveClusterOrganisation: 'The organisation',
    lightLoveClusterSupport: 'Help & participate',
    lightLoveClusterContact: 'Contact',
    lightLoveClusterAccount: 'Account',
    lightLoveInsightLabel: 'Key insight',
    lightLoveInsightTitle: 'The structure should start with what someone wants to do.',
    lightLoveInsightCopy: 'Someone looking for information about a visual impairment thinks differently from someone who wants to volunteer. That distinction gave us a clear foundation for the new information architecture.',
    lightLoveArchitectureLabel: 'New structure',
    lightLoveArchitectureTitle: 'From separate pages to clear destinations.',
    lightLoveArchitectureCopy: 'The card sorting confirmed that visitors primarily think in terms of their goal. We therefore simplified the navigation, regrouped related content and gave important actions a recognisable route of their own.',
    lightLoveArchitecturePathAria: 'From analysis to new navigation',
    lightLoveArchitectureStepOne: 'Existing structure',
    lightLoveArchitectureStepOneCopy: 'Make every page and dependency visible.',
    lightLoveArchitectureStepTwo: 'User logic',
    lightLoveArchitectureStepTwoCopy: 'Compare recurring groups and terminology.',
    lightLoveArchitectureStepThree: 'New navigation',
    lightLoveArchitectureStepThreeCopy: 'Organise content around information, participation and action.',
    lightLoveToBeLabel: 'TO-BE navigation',
    lightLoveHomeNode: 'Home as a clear starting point',
    lightLoveInformationGroup: 'Find information',
    lightLoveActionGroup: 'Take action',
    lightLoveSupportGroup: 'Supporting routes',
    lightLoveNavHelp: 'Support & information',
    lightLoveNavActivities: 'Activities',
    lightLoveNavAbout: 'About us',
    lightLoveNavNews: 'News & events',
    lightLoveNavVolunteer: 'Become a volunteer',
    lightLoveNavDonate: 'Donate',
    lightLoveNavContact: 'Get in touch',
    lightLoveSupportRoutes: 'FAQ · History · News detail · Register · Login routes',
    lightLoveArchitectureDecisionLabel: 'Design decision',
    lightLoveArchitectureDecisionCopy: 'Donating, volunteering and getting in touch were no longer hidden endpoints. Each received a clear route of its own, while content pages were grouped under recognisable destinations.',
    lightLovePrototypeLabel: 'Design development',
    lightLovePrototypeTitle: 'A structure only becomes useful in real screens.',
    lightLovePrototypeCopy: 'We translated the new navigation into an extensive desktop prototype. Clear page titles, recognisable routes and consistent locations for navigation and contact were intended to help visitors orient themselves faster.',
    lightLoveHomeScreenAria: 'Horizontally explorable homepage design',
    lightLoveHomeScreenAlt: 'Designed homepage for Blindenzorg Licht en Liefde.',
    lightLoveHomeScreenCaption: 'Home — overview, recognisable entry points and visible primary actions.',
    lightLoveHelpScreenAria: 'Horizontally explorable Support and information page design',
    lightLoveHelpScreenAlt: 'Designed Support and information page for Blindenzorg Licht en Liefde.',
    lightLoveHelpScreenCaption: 'Support & information — related guidance grouped under one clear destination.',
    lightLoveContactScreenAria: 'Horizontally explorable contact page design',
    lightLoveContactScreenAlt: 'Designed contact page for Blindenzorg Licht en Liefde.',
    lightLoveContactScreenCaption: 'Contact — form and location information together in a predictable place.',
    lightLovePrototypeNote: 'The prototype focuses on desktop. This gave us room to fully develop the complex content and navigation structure before testing it in a focused way.',
    lightLoveTestingLabel: 'Usability testing',
    lightLoveTestingTitle: 'Do not ask whether it is clear. Watch where someone gets stuck.',
    lightLoveTestingCopy: 'We tested the clickable prototype with six participants. Three sessions were moderated by the full project team; three additional tests were conducted separately. Repeating the same core tasks helped us compare recurring patterns instead of treating isolated opinions as evidence.',
    lightLoveTestParticipants: 'participants',
    lightLoveTestFactOne: 'Clickable desktop prototype in Figma',
    lightLoveTestFactTwo: 'Think-aloud and task-based observation',
    lightLoveTestFactThree: '3 team-moderated and 3 additional tests',
    lightLoveTasksLabel: '6 core tasks',
    lightLoveTaskOne: 'Find information about a visual impairment',
    lightLoveTaskTwo: 'Become a volunteer',
    lightLoveTaskThree: 'Find a workshop or activity',
    lightLoveTaskFour: 'Get in touch',
    lightLoveTaskFive: 'Start a donation',
    lightLoveTaskSix: 'Find the organisation’s history',
    lightLoveFindingsLabel: 'What we learned',
    lightLoveFindingsTitle: 'Four patterns determined what still had to change.',
    lightLoveFindingsCopy: 'Not every participant followed exactly the same route. The same moments of hesitation did recur. Those patterns gave us concrete priorities for the next iteration.',
    lightLoveFindingOneTitle: 'Workshops felt like activities.',
    lightLoveFindingOneEvidence: 'Participants looked for workshops under Activities first and then hesitated between Activities and News & events.',
    lightLoveFindingOneResponse: 'We therefore placed workshops directly under Activities and made the distinction with news clearer.',
    lightLoveFindingTwoTitle: 'The organisation’s history was buried too deeply.',
    lightLoveFindingTwoEvidence: 'Users expected the organisation’s story under About us, but only found its history after several steps.',
    lightLoveFindingTwoResponse: 'We made the route to the organisation’s story more visible and shortened the path towards it.',
    lightLoveFindingThreeTitle: 'Important actions needed more consistency.',
    lightLoveFindingThreeEvidence: 'Volunteering and donating were usually found, but CTAs varied in visibility. One older participant also mentioned small text and too many choices.',
    lightLoveFindingThreeResponse: 'We simplified copy, clarified headings and aligned the size and emphasis of action buttons more consistently.',
    lightLoveFindingFourTitle: 'The footer worked as a reliable anchor.',
    lightLoveFindingFourEvidence: 'Contact details and the address were found quickly and without hesitation at the bottom of the page.',
    lightLoveFindingFourResponse: 'We deliberately kept that predictable location instead of redesigning a pattern that already worked.',
    lightLoveOutcomeLabel: 'Final outcome',
    lightLoveOutcomeTitle: 'An evidence-based prototype for a complex information environment.',
    lightLoveOutcomeCopy: 'The outcome is an extensive desktop prototype that applies the new structure to the most important information and action pages. It was not launched as the official website; the value of the project lies in the complete process from analysis to tested refinement.',
    lightLoveOutcomeOne: 'New information architecture',
    lightLoveOutcomeTwo: 'Clickable desktop prototype',
    lightLoveOutcomeThree: 'Test-driven refinement',
    lightLoveReflectionLabel: 'Reflection',
    lightLoveReflectionTitle: 'A clear interface starts before the first screen.',
    lightLoveReflectionCopy: 'This project showed me how strongly information architecture shapes the complete user experience. As team lead, I learned to bring research, feedback and design decisions together without slowing down the process. The tests also made clear that a label that sounds logical does not automatically tell users where to look.',
    lightLoveContributionLabel: 'My contribution within the team',
    lightLoveContributionOne: 'Helping structure the process and feedback moments as team lead',
    lightLoveContributionTwo: 'Contributing to card sorting, information architecture and wireframes',
    lightLoveContributionThree: 'Facilitating usability tests and translating findings into iterations',
    lightLoveViewAllWork: 'View all projects',
    caseQuestionLabel: 'The design question',
    caseQuestionTitle: 'How do you make choosing easier without losing useful options?',
    caseQuestionCopy: 'A cinema app needs to offer information about films and planning, while keeping the choice of a film manageable. That balance between options and clarity guided the design.',
    caseFlowLabel: 'Structure',
    caseFlowTitle: 'Routes first, screens second.',
    caseFlowCopy: 'I mapped possible steps and functions, from finding a film to viewing details and choosing tickets. The flowchart shows the initial breadth of the concept and gave me a basis for organising the interface.',
    caseFlowAria: 'Scrollable Lumière flowchart',
    caseFlowAlt: 'Flowchart of the app concept with routes from the start to home, film listings, account and tickets.',
    caseFlowCaption: 'The information structure of the app concept. Scroll horizontally to explore the diagram in detail.',
    caseEvolutionLabel: 'Design development',
    caseEvolutionTitle: 'From structure to a recognisable interface.',
    caseEvolutionCopy: 'The home screen developed from a simple layout into a finished visual design. The three versions show how content, imagery and navigation found their places.',
    caseLowAlt: 'First low-fidelity version of the Lumière home screen.',
    caseLowLabel: 'Initial layout',
    caseMidAlt: 'Mid-fidelity version with imagery and content being placed.',
    caseMidLabel: 'Content and hierarchy',
    caseHighAlt: 'Finished high-fidelity version of the Lumière home screen.',
    caseHighLabel: 'Visual design',
    caseInsightLabel: 'Usability test',
    caseInsightTitle: 'Choosing a film should stay simple.',
    caseInsightCopy: 'The usability test indicated that too many options or a busy screen can confuse people when choosing a film. This made simplicity and clear choices important when evaluating the design.',
    caseOutcomeLabel: 'The outcome',
    caseOutcomeTitle: 'An interactive prototype as the outcome.',
    caseOutcomeCopy: 'The outcome is a finished home screen and an interactive Figma prototype of the wider app concept. The project taught me to weigh each feature against the simplicity of the experience.',
    caseNextAria: 'Continue browsing',
    burberryCaseDeck: 'Heritage, brought back into balance.',
    burberryCaseIntro: 'A personal rebrand study: how can a recognisable luxury brand feel calmer and more contemporary without losing its British character?',
    burberryOverviewTitle: 'Not a new brand. A sharper selection.',
    burberryOverviewCopy: "For this personal PET project, I explored how Burberry's familiar brand codes could be used with more restraint. The trench coat, the check and the historic rider were my starting points. My role was Brand Designer, from research and logo exploration to applications on clothing.",
    burberryContextValue: 'Personal PET project · conceptual rebrand',
    burberryScopeValue: 'Brand research, sketches, logo and clothing applications',
    burberryDirectionLabel: 'The direction',
    burberryDirectionTitle: 'What stays recognisable when you remove the noise?',
    burberryDirectionCopy: 'The study takes quiet luxury with archival heritage as its direction. Less visual noise, more attention to typography and space, and historic references used as details rather than decoration.',
    burberryExplorationLabel: 'Exploration',
    burberryExplorationTitle: 'Searching on paper first.',
    burberryExplorationCopy: 'The first sketches explore variations on the B, the shield and the historic rider. This exploration helped me choose a compact symbol that can remain visible at a small size on a garment.',
    burberrySketchAlt: 'Sheet of pencil sketches exploring Burberry monograms, shields and a rider.',
    burberrySketchCaption: 'Logo exploration: from rider and initials to a simpler mark.',
    burberryIdentityLabel: 'Identity',
    burberryIdentityTitle: 'A shield as a quiet reference.',
    burberryIdentityCopy: 'The developed symbol combines a B with a shield and a vertical line. It retains the ideas of protection and progress without repeating the full historic illustration. A serif wordmark provides an editorial counterpart.',
    burberryMarkAlt: 'The designed Burberry logo with a shield symbol and wordmark.',
    burberryMarkCaption: 'The complete logo from the original SVG design file.',
    burberryPaletteAria: 'Concept colour palette',
    burberryPaletteCopy: 'Ivory and black carry the identity; beige subtly references the trench coat.',
    burberryApplicationsLabel: 'Applications',
    burberryApplicationsTitle: 'The design on clothing.',
    burberryApplicationsCopy: 'The applications show two scales: a prominent wordmark and symbol on the black knit, and a more restrained mark as a detail on the trench coat and navy sweater. These are conceptual mockups, not manufactured garments.',
    burberryCoatDetailAlt: 'Trench coat with a Burberry label and subtle brand details.',
    burberryCoatCaption: '01 / Trench coat and label',
    burberryKnitDetailAlt: 'Black knit with a large Burberry wordmark and shield symbol.',
    burberryKnitCaption: '02 / Wordmark and symbol',
    burberrySweaterAlt: 'Navy sweater with a small shield symbol on the chest.',
    burberrySweaterCaption: '03 / Symbol as detail',
    burberryReflectionLabel: 'Reflection',
    burberryReflectionTitle: 'The strength lies in what you leave out.',
    burberryReflectionCopy: 'This project let me work with existing brand codes rather than starting from zero. The sketches, symbol and clothing mockups show the chosen direction. Other media, such as packaging or a website, are ideas in the project document and are not part of this developed selection.',
    burberryNextProject: 'View Lumière',
    footerRole: 'Designer & Developer focused on UX/UI.',
    skip: 'Skip to content',
    language: 'Language',
    description: 'Samuel Marquez Castro. Designer & Developer focused on UX/UI and visual design.'
  }
};

const metadata = {
  nl: {
    home: ['Samuel | Designer & Developer', 'Samuel Marquez Castro. Designer & Developer met een focus op UX/UI en visueel ontwerp.'],
    work: ['Werk | Samuel Marquez Castro', 'Geselecteerd UX/UI- en branddesignwerk van Samuel Marquez Castro.'],
    about: ['Over mij | Samuel Marquez Castro', 'Over Samuel Marquez Castro, Designer & Developer met een focus op UX/UI.'],
    contact: ['Contact | Samuel Marquez Castro', 'Neem contact op met Samuel Marquez Castro voor werk, stage of een kennismaking.'],
    lumiere: ['Lumière | Samuel Marquez Castro', 'Lumière: een individueel UX/UI-appconcept van Samuel Marquez Castro voor het vak Lab.'],
    burberry: ['Burberry | Samuel Marquez Castro', 'Burberry: een persoonlijke branddesignstudie van Samuel Marquez Castro rond erfgoed en eenvoud.'],
    lightLove: ['Licht & Liefde | Samuel Marquez Castro', 'Licht & Liefde: UX research, informatiearchitectuur en gebruikerstesten door Samuel Marquez Castro binnen een groepsproject.']
  },
  en: {
    home: ['Samuel | Designer & Developer', 'Samuel Marquez Castro. Designer & Developer focused on UX/UI and visual design.'],
    work: ['Work | Samuel Marquez Castro', 'Selected UX/UI and brand design work by Samuel Marquez Castro.'],
    about: ['About | Samuel Marquez Castro', 'About Samuel Marquez Castro, a Designer & Developer focused on UX/UI.'],
    contact: ['Contact | Samuel Marquez Castro', 'Contact Samuel Marquez Castro about work, an internship or an introduction.'],
    lumiere: ['Lumière | Samuel Marquez Castro', 'Lumière: an individual UX/UI app concept by Samuel Marquez Castro for his Lab course.'],
    burberry: ['Burberry | Samuel Marquez Castro', 'Burberry: a personal brand design study by Samuel Marquez Castro exploring heritage and simplicity.'],
    lightLove: ['Licht & Liefde | Samuel Marquez Castro', 'Licht & Liefde: UX research, information architecture and usability testing by Samuel Marquez Castro within a group project.']
  }
};

const language = new URLSearchParams(window.location.search).get('lang') === 'en' ? 'en' : 'nl';
const content = translations[language];
const page = document.body.dataset.page || 'home';

document.documentElement.lang = language;
document.title = metadata[language][page][0];
document.querySelector('meta[name="description"]').content = metadata[language][page][1];
document.querySelector('.language-switch').setAttribute('aria-label', content.language);

document.querySelectorAll('[data-i18n]').forEach(element => {
  element.textContent = content[element.dataset.i18n];
});
document.querySelectorAll('[data-i18n-alt]').forEach(image => {
  image.alt = content[image.dataset.i18nAlt];
});
document.querySelectorAll('[data-i18n-aria]').forEach(element => {
  element.setAttribute('aria-label', content[element.dataset.i18nAria]);
});
document.querySelectorAll('[data-language]').forEach(link => {
  if (link.dataset.language === language) link.setAttribute('aria-current', 'true');
  else link.removeAttribute('aria-current');
  link.href = `?lang=${link.dataset.language}${window.location.hash}`;
});
document.querySelectorAll('[data-page-link]').forEach(link => {
  const [path, hash] = link.dataset.pageLink.split('#');
  link.href = `${path}?lang=${language}${hash ? `#${hash}` : ''}`;
});
document.querySelector('.wordmark').href = `index.html?lang=${language}`;
document.querySelectorAll('[data-current-year]').forEach(element => {
  element.textContent = new Date().getFullYear();
});

// Eenmalige onthullingen, alleen wanneer de browser en bewegingsvoorkeur dat toelaten.
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
if ('IntersectionObserver' in window && !reducedMotion.matches) {
  const sections = document.querySelectorAll('.introduction, .project-heading, .project-stage, .project-context, .page-hero, .work-row, .about-portrait, .about-story, .process-grid, .services-grid, .contact-panel, .contact-details, .case-overview, .case-question, .case-section-heading, .case-flow-figure, .case-evolution-grid, .case-insight, .case-outcome, .burberry-overview, .burberry-principle, .burberry-section-heading, .burberry-sketch, .burberry-mark-stage, .burberry-application-grid, .burberry-reflection, .light-love-overview > div, .light-love-section-heading, .light-love-card-method, .light-love-card-insight, .light-love-architecture-path, .light-love-architecture-decision, .light-love-test-method, .light-love-test-tasks, .light-love-findings-list li, .light-love-outcome-points, .light-love-reflection-copy, .light-love-contribution');
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      entry.target.classList.add('is-revealed');
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.08, rootMargin: '0px 0px -6% 0px' });
  sections.forEach(section => {
    section.classList.add('reveal-pending');
    observer.observe(section);
  });
  reducedMotion.addEventListener('change', event => {
    if (!event.matches) return;
    observer.disconnect();
    sections.forEach(section => section.classList.remove('reveal-pending'));
  }, { once: true });
}

// Lichte scrollregie op de homepage. De beweging blijft klein en volgt alleen de
// compositie; bij reduced motion worden er geen inline transforms aangestuurd.
const homeHero = document.querySelector('.hero');
const homeStages = document.querySelectorAll('.selected-work .project-stage');

if (homeHero && homeStages.length && !reducedMotion.matches) {
  let scrollFrame;

  const updateScrollComposition = () => {
    scrollFrame = undefined;
    const viewportHeight = window.innerHeight || 1;
    const heroProgress = Math.min(Math.max(window.scrollY / viewportHeight, 0), 1);
    const heroTitle = homeHero.querySelector('h1');

    heroTitle.style.setProperty('--hero-shift', `${heroProgress * -36}px`);
    heroTitle.style.setProperty('--hero-opacity', String(1 - heroProgress * .34));

    homeStages.forEach(stage => {
      const bounds = stage.getBoundingClientRect();
      const centerDifference = bounds.top + bounds.height / 2 - viewportHeight / 2;
      const progress = Math.min(Math.max(centerDifference / viewportHeight, -1), 1);
      stage.style.setProperty('--identity-shift', `${progress * -18}px`);
      stage.style.setProperty('--device-shift', `${progress * 28}px`);
      stage.style.setProperty('--logo-shift', `${progress * -14}px`);
      stage.style.setProperty('--coat-shift', `${progress * 24}px`);
      stage.style.setProperty('--knit-shift', `${progress * -18}px`);
    });
  };

  const requestScrollComposition = () => {
    if (scrollFrame) return;
    scrollFrame = window.requestAnimationFrame(updateScrollComposition);
  };

  updateScrollComposition();
  window.addEventListener('scroll', requestScrollComposition, { passive: true });
  window.addEventListener('resize', requestScrollComposition);

  reducedMotion.addEventListener('change', event => {
    if (!event.matches) return;
    window.removeEventListener('scroll', requestScrollComposition);
    window.removeEventListener('resize', requestScrollComposition);
    homeHero.querySelector('h1').removeAttribute('style');
    homeStages.forEach(stage => {
      stage.style.removeProperty('--identity-shift');
      stage.style.removeProperty('--device-shift');
      stage.style.removeProperty('--logo-shift');
      stage.style.removeProperty('--coat-shift');
      stage.style.removeProperty('--knit-shift');
    });
  }, { once: true });
}
